services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/opt/mysql/data
      - ./log:/var/opt/mysql/log
      - ./secrets:/var/opt/mysql/secrets
